In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
import warnings
warnings.filterwarnings("ignore")

In [2]:
salaries=pd.read_csv("salaries.csv")
salaries

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [3]:
input=salaries.drop("salary_more_then_100k",axis = 1)
input

company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [4]:
target = salaries[["salary_more_then_100k"]]
target

salary_more_then_100k
0                       0
1                       0
2                       1
3                       1
4                       0
5                       1
6                       0
7                       0
8                       0
9                       1
10                      1
11                      1
12                      1
13                      1
14                      1
15                      1

In [5]:
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

In [6]:
input

company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [30]:
#using fit transform
input["company_x"]=le_company.fit_transform(input["company"])
input["job_x"]=le_job.fit_transform(input["job"])
input["degree_x"]=le_degree.fit_transform(input["degree"])

In [8]:
input

company                  job     degree  company_x  job_x  degree_x
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

In [9]:
#drop the initial columns(company	job	degree	)
final_dummy =input.drop(["company","job","degree"], axis = 1)
final_dummy

company_x  job_x  degree_x
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [9]:
target

salary_more_then_100k
0                       0
1                       0
2                       1
3                       1
4                       0
5                       1
6                       0
7                       0
8                       0
9                       1
10                      1
11                      1
12                      1
13                      1
14                      1
15                      1

In [11]:
model = tree.DecisionTreeClassifier()
model

DecisionTreeClassifier()

In [12]:
model.fit(final_dummy,target)

DecisionTreeClassifier()

In [13]:
model.score(final_dummy,target)

1.0

In [14]:
input

company                  job     degree  company_x  job_x  degree_x
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

In [15]:
model.predict([[2,1,0]])

array([0], dtype=int64)

In [16]:
model.predict([[2,1,1]])

array([1], dtype=int64)

In [17]:
model.predict([[1,1,1]])

array([1], dtype=int64)

# RANDOM FOREST

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.datasets import load_digits
sns.set 
digits = load_digits()
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [32]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [33]:
df=pd.DataFrame(digits.data)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [34]:
df["targets"]=digits.target

In [35]:
df[0:12]

0    1     2     3     4     5     6    7    8    9  ...   55   56   57  \
0   0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1   0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2   0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3   0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4   0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5   0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6   0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
7   0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
8   0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9   0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0  2.0  ...  0.0  0.0  0.0   
10  0.0  0.0   1.0   9.0  15.0  11.0   0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
11  0.0  0.0   0.0   0.0  14.0  13.0   1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      58    59    60    61   62   63  targets  
0    6.0  13.0  10.0   0.0  0.0  0.0        0  
1    0.0  11.0  16.0  10.0  0.0  0.0        1  
2    0.0   3.0  11.0  16.0  9.0  0.0        2  
3    7.0  13.0  13.0   9.0  0.0  0.0        3  
4    0.0   2.0  16.0   4.0  0.0  0.0        4  
5    9.0  16.0  16.0  10.0  0.0  0.0        5  
6    1.0   9.0  15.0  11.0  3.0  0.0        6  
7   13.0   5.0   0.0   0.0  0.0  0.0        7  
8   11.0  16.0  15.0  11.0  1.0  0.0        8  
9    9.0  12.0  13.0   3.0  0.0  0.0        9  
10   1.0  10.0  13.0   3.0  0.0  0.0        0  
11   0.0   1.0  13.0  16.0  1.0  0.0        1  

[12 rows x 65 columns]

In [36]:
x=df.drop("targets",axis = 1)
y=df.targets

In [37]:
X_train, X_test, y_train, y_test=train_test_split(x,y, test_size = 0.2)

In [38]:
model = RandomForestClassifier( n_estimators = 20)
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=20)

In [39]:
y_test

213     3
1118    3
472     7
57      2
911     6
       ..
519     3
148     8
380     4
1531    2
1611    4
Name: targets, Length: 360, dtype: int32

In [40]:
X_test

0    1     2     3     4     5     6    7    8    9   ...    54   55  \
213   0.0  2.0  14.0  16.0  12.0   6.0   0.0  0.0  0.0  1.0  ...   2.0  0.0   
1118  0.0  0.0   3.0  11.0  14.0  12.0   3.0  0.0  0.0  2.0  ...   0.0  0.0   
472   0.0  0.0   6.0  15.0   8.0  10.0  12.0  2.0  0.0  0.0  ...   0.0  0.0   
57    0.0  0.0   0.0   1.0   9.0  11.0   0.0  0.0  0.0  0.0  ...   4.0  0.0   
911   0.0  0.0   1.0  10.0  10.0   0.0   0.0  0.0  0.0  1.0  ...  11.0  0.0   
...   ...  ...   ...   ...   ...   ...   ...  ...  ...  ...  ...   ...  ...   
519   0.0  0.0   1.0   9.0  15.0   5.0   0.0  0.0  0.0  0.0  ...  15.0  0.0   
148   0.0  0.0   3.0  13.0  13.0   3.0   0.0  0.0  0.0  2.0  ...   7.0  0.0   
380   0.0  0.0   0.0   6.0  16.0   2.0   0.0  0.0  0.0  0.0  ...   0.0  0.0   
1531  0.0  2.0  15.0  13.0   2.0   0.0   0.0  0.0  0.0  7.0  ...  11.0  0.0   
1611  0.0  0.0  10.0  14.0   0.0   0.0   0.0  0.0  0.0  1.0  ...   0.0  0.0   

       56   57    58    59    60    61    62   63  
213   0.0  3.0  13.0  11.0   7.0   2.0   0.0  0.0  
1118  0.0  3.0   7.0  14.0   5.0   0.0   0.0  0.0  
472   0.0  0.0   7.0  14.0   0.0   0.0   0.0  0.0  
57    0.0  0.0   0.0   0.0   9.0  13.0   3.0  0.0  
911   0.0  0.0   1.0  12.0  16.0  14.0   2.0  0.0  
...   ...  ...   ...   ...   ...   ...   ...  ...  
519   0.0  0.0   1.0  10.0  16.0  15.0  11.0  1.0  
148   0.0  0.0   3.0  13.0  16.0  10.0   1.0  0.0  
380   0.0  0.0   0.0  10.0  15.0   0.0   0.0  0.0  
1531  0.0  2.0  15.0  13.0   6.0   4.0   1.0  0.0  
1611  0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  

[360 rows x 64 columns]

In [41]:
model.score(X_test,y_test)

0.9472222222222222

In [42]:
df[45:55]

0    1     2     3     4     5    6    7    8    9  ...   55   56   57  \
45  0.0  0.0   9.0  16.0  13.0   6.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
46  0.0  1.0  15.0   4.0   0.0   0.0  0.0  0.0  0.0  2.0  ...  0.0  0.0  0.0   
47  0.0  0.0   0.0   1.0  11.0   9.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
48  0.0  0.0   2.0  15.0  13.0   3.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
49  0.0  0.0   1.0  15.0  13.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
50  0.0  0.0   0.0   5.0  14.0  12.0  2.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
51  0.0  0.0   0.0   3.0  15.0  10.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
52  0.0  0.0   3.0  12.0  16.0  16.0  6.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
53  0.0  0.0   4.0   8.0  16.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
54  0.0  0.0   0.0   1.0  14.0  14.0  3.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      58    59    60    61   62   63  targets  
45  11.0  14.0  12.0   8.0  0.0  0.0        3  
46  14.0  14.0   4.0   0.0  0.0  0.0        5  
47   0.0   2.0  14.0   6.0  0.0  0.0        1  
48   4.0  12.0  15.0   6.0  0.0  0.0        0  
49   0.0  13.0  14.0   8.0  0.0  0.0        0  
50   0.0   6.0  12.0  13.0  3.0  0.0        2  
51   0.0   4.0   9.0  14.0  7.0  0.0        2  
52   4.0  16.0   5.0   0.0  0.0  0.0        7  
53   6.0  16.0  12.0   1.0  0.0  0.0        8  
54   0.0   1.0  13.0  16.0  5.0  0.0        2  

[10 rows x 65 columns]